---
title: "Homework 6"
author: "Vanessa Dinh"
date: 12/1/22
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

```

## Problem 2

```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

raw_wapo_homocide = 
  read_csv(url) %>% 
  janitor::clean_names()

```

```{r}
wapo_homocide =
  raw_wapo_homocide %>% 
  mutate(
    city_state = paste(city, state, sep = ", "),
    disposition = as.factor(disposition),
    city_state = as.factor(city_state),
    uid = as.factor(uid),
    victim_age = as.numeric(victim_age),
    victim_sex = as.factor(victim_sex),
    resolved_homocide = as.numeric(disposition == "Closed by arrest")
  ) %>% 
  filter(city_state != "Dallas, TX" | city_state != "Phoenix, AZ" | city_state != "Kansas City, MO") %>%      filter(city_state != "Tulsa, AL") %>% 
  filter(victim_race == "White" | victim_race == "Black") %>% 
  mutate(
    victim_race = fct_relevel(victim_race, "White")
  ) %>% 
  filter(!is.na(victim_age)) %>% 
  filter(victim_sex == "Male" | victim_sex == "Female") %>% 
  mutate(victim_sex = fct_relevel(victim_sex, "Male", "Female")) %>% 
  droplevels() %>% 
  nest_by(city_state)

```

```{r}
balti_glm_logistic =
  wapo_homocide %>% 
  filter(city_state == "Baltimore, MD") %>% 
  unnest(data) %>% 
  select(resolved_homocide, victim_age, victim_race, victim_sex) %>% 
  glm(resolved_homocide ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 
```

```{r}
balti_glm_logistic %>% 
  broom::tidy() %>% 
  mutate(
     adjusted_OR = exp(estimate),
     estimate_lower_CI = estimate - (1.96*std.error),
     estimate_upper_CI = estimate + (1.96*std.error),
     OR_lower_CI = exp(estimate_lower_CI),
     OR_upper_CI = exp(estimate_upper_CI)) %>% 
  filter(term == "victim_sexFemale") %>% 
  select(term, adjusted_OR, OR_lower_CI, OR_upper_CI) %>% 
  knitr::kable(digits = 3)
```

```{r message = FALSE}
city_glm = function(x) {
  
  city_glm_df =
  wapo_homocide %>% 
  filter(city_state == x) %>% 
  unnest(data) %>% 
  select(resolved_homocide, victim_age, victim_race, victim_sex) %>% 
  glm(resolved_homocide ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 
  
  city_glm_df %>% 
  broom::tidy() %>% 
  mutate(
     adjusted_OR = exp(estimate),
     estimate_lower_CI = estimate - (1.96*std.error),
     estimate_upper_CI = estimate + (1.96*std.error),
     OR_lower_CI = exp(estimate_lower_CI),
     OR_upper_CI = exp(estimate_upper_CI)) %>% 
  filter(term == "victim_sexFemale") %>% 
  select(adjusted_OR, OR_lower_CI, OR_upper_CI)
}

final_glm_df = 
  wapo_homocide %>% 
  mutate(summary = map(city_state, city_glm)) %>% 
  select(city_state, summary) %>% 
  unnest(summary)
```


```{r}
final_glm_df %>% 
  knitr::kable(digits = 3)
```

```{r fig.align = "center", fig.width = 10}
final_glm_df %>% 
  ggplot(aes(x = reorder(city_state, adjusted_OR), y = adjusted_OR)) +
  geom_point(aes(x = reorder(city_state, adjusted_OR), y = adjusted_OR), color = "deepskyblue3") +
  geom_errorbar(aes(ymin = OR_lower_CI, ymax = OR_upper_CI), color = "deepskyblue3", width = 0.5) +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides Comparing Male to Female Victims",
    x = "US Cities",
    y = "Adjusted OR for Solving Homocides (95% CI)"
  ) +
  theme(legend.position = "none") +
  scale_x_discrete(
    guide = guide_axis(angle = 40)
  ) 
```

